export const FETCH_TEST_REQUEST = "FETCH_TEST_REQUEST";
export const FETCH_TEST_SUCCESS = "FETCH_TEST_SUCCESS";
export const CHANGE_ANSWER_CORRECT_STATE = "CHANGE_ANSWER_CORRECT_STATE";
export const CHANGE_I_AM_SURE_IN_ANSWER_STATE = "CHANGE_I_AM_SURE_IN_ANSWER_STATE";

export const FETCH_TESTS_REQUEST = "FETCH_TESTS_REQUEST";
export const FETCH_TESTS_SUCCESS = "FETCH_TESTS_SUCCESS";